#!/usr/bin/with-contenv sh

s6-setuidgid abc exec /usr/sbin/openvpn \
	--writepid /config/openvpn/pid \
	--config ${OPENVPN_CONFIG} \
	--auth-user-pass /config/openvpn-credentials.txt \
	--auth-nocache \
	--dev tun0 --persist-tun \
	--iproute /usr/sbin/ip-su 