#!/usr/bin/with-contenv sh

/usr/sbin/openvpn --mktun --dev 'tun0' --dev-type 'tun' --user 'abc' --group 'abc'  > '/dev/null'

usermod -G netdev abc

mkdir -p '/var/log/netmon'

if [ -e "${OPENVPN_USERNAME}" ] || [ -e "${OPENVPN_PASSWORD}" ] ; then
 echo "OpenVPN credentials not set. Exiting."
 exit 1
else
  echo "Setting OPENVPN credentials..."
  mkdir -p /config
  echo $OPENVPN_USERNAME > /config/openvpn-credentials.txt
  echo $OPENVPN_PASSWORD >> /config/openvpn-credentials.txt
  chmod 600 /config/openvpn-credentials.txt
fi