#!/usr/bin/with-contenv sh

config=$VPN_CONFIG

if [ ! -e "${config}" ]; then
	printf "ERROR: '%s' not mounted\n" "${config}"
	exit 1
fi

rules='/tmp/ipv4-rules'
proto=$(awk '/proto / { print $2 }' "${config}")
host=$(awk '/remote / { print $2 }' "${config}")
port=$(awk '/remote / { print $3 }' "${config}")

cat '/etc/iptables/rules' > "${rules}"

sed "s/{PROTO}/${proto}/g; s/{HOST}/${host}/g; s/{PORT}/${port}/g" \
	"${rules}" | iptables-restore