#!/bin/sh
rules='/tmp/ipv6-rules'

if [ $(ifconfig -a | grep -c 'inet6') -eq 0 ]; then
	exit 0
fi

cat '/etc/iptables/default-policy' \
	'/etc/iptables/commit-rules' > "${rules}"

ip6tables-restore < "${rules}"